import FounderBrief from './FounderBrief.jsx';
import Paged from './Paged.jsx';
import CustomerHealth from './CustomerHealth.jsx';
import Connections from './Connections.jsx';
import MarketIntelligence from './MarketIntelligence.jsx';
import CompanyQuestions from './CompanyQuestions.jsx';
import React, { useEffect, useState } from 'react';
import CompanyEditor from './CompanyEditor.jsx';
import CompanyGraph from './CompanyGraph.jsx';
import DecisionMemory from './DecisionMemory.jsx';
import ScenarioPlanner from './ScenarioPlanner.jsx';
import TeamIntelligence from './TeamIntelligence.jsx';
const money = (minor, currency) => `${currency} ${(minor / 100).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
export function sampleSnapshot() {
  const now = new Date();
  const date = offset => new Date(now.getTime() + offset * 86400000).toISOString().slice(0, 10);
  return { importKey: `sample-${crypto.randomUUID()}`, observedAt: now.toISOString(), source: { kind: 'sample', name: 'Synthetic Genesis demo — not real company data' }, currency: 'USD', teams: [{ id: 'engineering', name: 'Engineering' }], employees: [{ id: 'alex', name: 'Alex (sample)', teamId: 'engineering', capacityHours: 40, allocatedHours: 56 }, { id: 'sam', name: 'Sam (sample)', teamId: 'engineering', capacityHours: 40, allocatedHours: 51 }], projects: [{ id: 'alpha', name: 'Project Alpha', teamId: 'engineering', ownerIds: ['alex', 'sam'], dueDate: date(-16), completion: 60 }], products: [{ id: 'platform', name: 'Platform' }], features: [{ id: 'sync', name: 'Account sync', projectId: 'alpha', productId: 'platform' }], customers: [{ id: 'acme', name: 'Acme (sample)', featureIds: ['sync'], requestedFeatureIds: ['sync'], arrMinor: 4000000, renewalDate: date(31), openSupportIssues: 4 }, { id: 'north', name: 'North (sample)', featureIds: ['sync'], requestedFeatureIds: ['sync'], arrMinor: 2500000, renewalDate: date(44), openSupportIssues: 2 }, { id: 'river', name: 'River (sample)', featureIds: ['sync'], requestedFeatureIds: ['sync'], arrMinor: 1800000, renewalDate: date(90), openSupportIssues: 1 }] };
}
const categories = { capacity_delivery: 'Capacity & delivery', renewal_attention: 'Customer renewal', customer_concentration: 'Revenue concentration', feature_demand: 'Product opportunity', customer_health: 'Customer health', customer_expansion: 'Customer expansion', market_change: 'Market impact' };
const statuses = ['open', 'in_progress', 'completed', 'cancelled'];
function Evidence({ signal }) {
  const e = signal.evidence;
  const metrics = signal.category === 'capacity_delivery' ? [[`${e.allocatedHours} / ${e.capacityHours}h`, 'Allocation / capacity'], [`${e.delayDays} days`, 'Overdue delivery']] : signal.category === 'renewal_attention' ? [[`${e.daysToRenewal} days`, 'Until renewal'], [e.delayedFeatureCount, 'Delayed feature dependencies']] : signal.category === 'customer_concentration' ? [[`${e.concentrationPct}%`, 'Share of imported ARR'], [e.payingCustomerCount, 'Paying accounts imported']] : signal.category === 'feature_demand' ? [[e.customerCount, 'Explicit customer requests']] : [[e.customerCount, 'Connected customers'], [e.supportIssues ?? 'Unknown', 'Open support issues']];
  return <div className="evidence-metrics">{[...metrics, [money(e.arrMinor, e.currency), 'Connected customer ARR']].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>;
}
function ActionForm({ signal, employees, busy, onCreate }) {
  return <form className="action-form" onSubmit={e => { e.preventDefault(); onCreate({ ...Object.fromEntries(new FormData(e.currentTarget)), riskKey: signal.key }); }}>
    <label>Action<input name="title" defaultValue={signal.recommendations[0]} maxLength={160} required /></label>
    <div className="form-pair"><label>Owner<select name="ownerId" required defaultValue=""><option value="" disabled>Select an owner</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Due date<input name="dueDate" type="date" required /></label></div>
    <label>Why this decision?<input name="reason" maxLength={2000} required /></label><label>Expected result<input name="expectedResult" placeholder="Describe an observable outcome" maxLength={2000} required /></label><button disabled={busy || !employees.length}>{busy ? 'Saving…' : 'Assign action'}</button>{!employees.length && <p className="muted">Import an employee before assigning an action.</p>}
  </form>;
}
function SignalCard({ signal, snapshot, busy, readOnly, onCreate, actionCount }) {
  const [expanded, setExpanded] = useState(false), [assigning, setAssigning] = useState(false);
  const label = signal.severity === 'opportunity' ? 'Opportunity' : signal.severity === 'critical' ? 'Act soon' : 'Review';
  return <article className={`priority-card ${signal.severity}`}>
    <div className="card-top"><span className={`signal-badge ${signal.severity}`}>{label}</span><span className="muted">{categories[signal.category]}</span>{actionCount > 0 && <span className="action-count">{actionCount} action{actionCount === 1 ? '' : 's'}</span>}</div>
    <h3>{signal.title}</h3><p>{signal.explanation}</p><Evidence signal={signal}/>
    <div className="card-controls"><button className="quiet-button" aria-expanded={expanded} aria-controls={`evidence-${signal.key}`} onClick={() => setExpanded(!expanded)}>{expanded ? 'Hide evidence ↑' : 'Explore evidence ↓'}</button>{!readOnly && <button className="quiet-button" aria-expanded={assigning} aria-controls={`assign-${signal.key}`} onClick={() => setAssigning(!assigning)}>{assigning ? 'Close action form' : 'Assign an action →'}</button>}</div>
    <div id={`evidence-${signal.key}`} hidden={!expanded} className="expanded-evidence"><h4>Why it matters</h4><p>{signal.consequence}</p><h4>Suggested next steps</h4><ul>{signal.recommendations.map(r => <li key={r}>{r}</li>)}</ul>
      {!!signal.paths.length && <><h4>Connected work</h4><ul className="relationship-list">{signal.paths.map((p, i) => <li key={i}><span>{snapshot.teams.find(t => t.id === p.teamId)?.name}</span> → <span>{snapshot.projects.find(t => t.id === p.projectId)?.name}</span> → <span>{snapshot.features.find(t => t.id === p.featureId)?.name}</span> → <span>{snapshot.customers.find(t => t.id === p.customerId)?.name}</span><small>Owners: {p.employeeIds.map(id => snapshot.employees.find(e => e.id === id)?.name).join(', ') || 'Unassigned'}</small></li>)}</ul></>}
      {signal.sourceUrl && <p><a href={signal.sourceUrl} target="_blank" rel="noreferrer">Open recorded market source</a></p>}<h4>Customer evidence</h4><div className="table-scroll"><table><thead><tr><th>Customer</th><th>ARR</th><th>Renewal</th><th>Open issues</th></tr></thead><tbody>{signal.customers.map(c => <tr key={c.id}><td>{c.name}</td><td>{money(c.arrMinor, signal.evidence.currency)}</td><td>{c.renewalDate || 'Unknown'}</td><td>{c.openSupportIssues}</td></tr>)}</tbody></table></div>
      <p className="muted">{signal.confidence}. Customer ARR is deduplicated in the attention summary.</p>{signal.category === 'capacity_delivery' && <p className="muted">Workload change: {signal.evidence.workloadChangePct === null ? 'unknown — a comparable baseline is needed' : `${signal.evidence.workloadChangePct}%`}</p>}
    </div>
    <div id={`assign-${signal.key}`} hidden={!assigning}>{assigning && <ActionForm signal={signal} employees={snapshot.employees} busy={busy} onCreate={async input => { if (await onCreate(input)) setAssigning(false); }}/>}</div>
  </article>;
}
export default function CommandCenter({ workspace, request, token, view, onNavigate: setView }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [draft, setDraft] = useState('');
  const [filter, setFilter] = useState('all'), [focusedSignal, setFocusedSignal] = useState(null), [query, setQuery] = useState(''), [actionFilter, setActionFilter] = useState('active');
  useEffect(() => { const clear = () => { setFocusedSignal(null); setFilter('all'); setQuery(''); }; window.addEventListener('genesis:nav-link', clear); return () => window.removeEventListener('genesis:nav-link', clear); }, []);
  const root = `/api/workspaces/${workspace._id}/intelligence`;
  const load = async () => setData(await request(root, {}, token));
  useEffect(() => { let active = true; request(root, {}, token).then(v => { if (active) setData(v); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [root, token]);
  async function perform(fn, message = 'Saved successfully.') { setBusy(true); setError(''); setNotice(''); try { await fn(); await load(); setNotice(message); return true; } catch (e) { setError(e.message); return false; } finally { setBusy(false); } }
  const send = (path, body, method = 'POST') => request(`${root}${path}`, { method, body: JSON.stringify(body) }, token);
  const latest = data?.latest, analysis = latest?.analysis, snapshot = latest?.snapshot;
  const readOnly = workspace.members?.find(m => { try { const payload = JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/'))); return m.userId === payload.sub; } catch { return false; } })?.role === 'viewer';
  const signals = [...(analysis?.risks || []), ...(analysis?.customerSignals || []), ...(analysis?.marketSignals || [])].sort((a, b) => ({ critical: 0, warning: 1, opportunity: 2 }[a.severity] - { critical: 0, warning: 1, opportunity: 2 }[b.severity]) || b.evidence.arrMinor - a.evidence.arrMinor || a.key.localeCompare(b.key));
  const visible = signals.filter(s => (!focusedSignal || s.key === focusedSignal) && (filter === 'all' || (filter === 'opportunity' ? s.severity === 'opportunity' : filter === 'attention' ? s.severity !== 'opportunity' : s.category === filter)) && `${s.title} ${s.explanation} ${s.customers.map(c => c.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const activeActions = (data?.actions || []).filter(a => !['completed', 'cancelled'].includes(a.status));
  const actions = (data?.actions || []).filter(a => actionFilter === 'all' || (actionFilter === 'active' ? !['completed', 'cancelled'].includes(a.status) : a.status === actionFilter));
  return <section className="command-center" aria-busy={busy}>
    <div aria-live="polite">{notice && <p className="success-notice" role="status">✓ {notice}</p>}</div>{error && <p role="alert" className="error">{error}</p>}
    {!data && !error && <p role="status">Loading company intelligence…</p>}
    {view === 'home' && data && <FounderBrief data={data} signals={signals} onNavigate={setView} onSignal={key => { setFocusedSignal(key); setFilter('all'); setQuery(''); setView('priorities'); }}/>}
    {view === 'priorities' && latest && <div className="page-tools"><span className="muted">Evidence observed {new Date(snapshot.observedAt).toLocaleDateString()}</span><button className="quiet-button" disabled={busy || readOnly} onClick={() => perform(() => send('/evaluate', {}), 'Signals refreshed.')}>{busy ? 'Refreshing…' : '↻ Refresh signals'}</button></div>}
    {view === 'priorities' && <>
      {!latest && data && <div className="empty-state"><h3>Start with your company’s connections.</h3><p>Import your team, project, and customer data to discover what needs attention.</p><button onClick={() => setView('data')}>Set up company data →</button></div>}
      {analysis && <>{focusedSignal && <p className="success-notice">Showing a selected company signal. <button className="quiet-button" onClick={() => setFocusedSignal(null)}>Show all priorities</button></p>}<div className="priority-toolbar"><label className="search-label">Search priorities<input type="search" placeholder="Search a customer, project, or signal…" value={query} onChange={e => setQuery(e.target.value)}/></label><label>Show<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All signals</option><option value="attention">Needs review</option><option value="opportunity">Opportunities</option>{Object.entries(categories).filter(([key]) => key !== 'feature_demand').map(([key, title]) => <option key={key} value={key}>{title}</option>)}</select></label></div><p className="muted" role="status">{visible.length} of {signals.length} signals · Prioritized by urgency, then connected ARR</p>
      {!visible.length && <div className="empty-state"><h3>{signals.length ? 'No matching priorities' : 'No current signals'}</h3><p>{signals.length ? 'Try a different search or filter.' : 'No rules trigger on this observation. This is not a complete assessment of company health.'}</p>{signals.length > 0 && <button onClick={() => { setQuery(''); setFilter('all'); setFocusedSignal(null); }}>Clear filters</button>}</div>}
      <Paged items={visible} size={2} resetKey={`${filter}:${query}:${focusedSignal}`} >{signal => <SignalCard key={signal.key} signal={signal} snapshot={snapshot} busy={busy} readOnly={readOnly} actionCount={(data.actions || []).filter(a => a.riskKey === signal.key && !['completed', 'cancelled'].includes(a.status)).length} onCreate={input => perform(() => send('/actions', input), 'Action assigned. Track progress in Actions.')}/>}</Paged></>}
    </>}
    {data && <div hidden={view !== 'map'}><CompanyGraph snapshot={snapshot} signals={signals} actions={data.actions || []} onOpenData={() => setView('data')} onOpenActions={() => { setView('actions'); setActionFilter('all'); }} onOpenSignal={key => { setFocusedSignal(key); setFilter('all'); setQuery(''); setView('priorities'); }}/></div>}
    {data && <div hidden={view !== 'customers'}><CustomerHealth snapshot={snapshot} health={analysis?.customerHealth} signals={signals} onData={() => setView('data')} onPriority={key => { setFocusedSignal(key); setFilter('all'); setQuery(''); setView('priorities'); }}/></div>}
    {view === 'connections' && <Connections root={root} request={request} token={token} snapshot={snapshot} actions={data?.actions || []} readOnly={readOnly} onChanged={load}/>}
    {view === 'market' && <MarketIntelligence root={root} workspaceId={workspace._id} request={request} token={token} snapshot={snapshot} signals={signals} readOnly={readOnly} onChanged={load} onPriority={key => { setFocusedSignal(key); setFilter('all'); setQuery(''); setView('priorities'); }}/>}
    {view === 'questions' && <CompanyQuestions root={root} request={request} token={token} readOnly={readOnly} onNavigate={target => { setFocusedSignal(null); setFilter('all'); setQuery(''); setView(target); }}/>}
    {data && <div hidden={view !== 'teams'}><TeamIntelligence health={analysis?.teamHealth} snapshot={snapshot} signals={signals} actions={data.actions || []} readOnly={readOnly} busy={busy} onRefresh={() => perform(() => send('/evaluate', {}), 'Team analysis updated.')} onData={() => setView('data')} onPriority={key => { setFocusedSignal(key); setFilter('all'); setQuery(''); setView('priorities'); }} onActions={() => { setActionFilter('all'); setView('actions'); }} onDecisions={() => setView('decisions')}/></div>}
    {data && <div hidden={view !== 'scenarios'}><ScenarioPlanner forecast={data.forecast} financial={data.financial} snapshot={snapshot} scenarios={data.scenarios || []} busy={busy} readOnly={readOnly} onSaveFinancial={input => perform(() => request(`/api/workspaces/${workspace._id}/financials`, { method: 'POST', body: JSON.stringify(input) }, token), 'Financial baseline saved.')} onCreate={input => perform(() => send('/scenarios', input), 'Scenario calculated and saved.')}/></div>}
    {data && <div hidden={view !== 'decisions'}><DecisionMemory decisions={data.decisions || []} snapshot={snapshot} signals={signals} actions={data.actions || []} busy={busy} readOnly={readOnly} onCreate={input => perform(() => send('/decisions', input), 'Decision recorded with its original reasoning.')} onReview={(id, input) => perform(() => send(`/decisions/${id}/reviews`, input), 'Outcome and lesson added to decision history.')} onOpenActions={() => { setView('actions'); setActionFilter('all'); }}/></div>}
    {view === 'actions' && <section className="actions"><div className="section-heading"><h3>Decisions into progress</h3><label>Show actions<select value={actionFilter} onChange={e => setActionFilter(e.target.value)}><option value="active">Active</option><option value="all">All</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label></div>{!actions.length && <div className="empty-state"><h3>No {actionFilter === 'all' ? '' : actionFilter} actions yet</h3><p>Assign an action from a priority to give it an owner and a measurable outcome.</p><button onClick={() => setView('priorities')}>Review priorities →</button></div>}<Paged items={actions} size={3} resetKey={actionFilter}>{a => <article key={a._id}><div className="card-top"><span className="signal-badge">{a.status.replaceAll('_', ' ')}</span>{a.dueDate < new Date().toISOString().slice(0, 10) && !['completed', 'cancelled'].includes(a.status) && <span className="error">Overdue</span>}</div><h4>{a.title}</h4><p>{a.ownerName} · Due {a.dueDate}</p><label>Status<select aria-label={`Status for ${a.title}`} disabled={busy || readOnly} value={a.status} onChange={e => perform(() => send(`/actions/${a._id}`, { status: e.target.value }, 'PATCH'), 'Action status updated.')}>{statuses.map(s => <option value={s} key={s}>{s.replaceAll('_', ' ')}</option>)}</select></label><details><summary>Decision & outcome</summary><p>Reason: {a.reason}</p><p>Expected: {a.expectedResult}</p><p>{a.outcome?.message}</p>{a.outcome?.current && <p className="muted">Connected ARR: {money(a.outcome.baseline.arrMinor, a.outcome.baseline.currency)} → {money(a.outcome.current.arrMinor, a.outcome.current.currency)}{a.outcome.current.allocatedHours !== undefined && ` · Allocation: ${a.outcome.baseline.allocatedHours} → ${a.outcome.current.allocatedHours}h`}{a.outcome.current.supportIssues !== undefined && ` · Open issues: ${a.outcome.baseline.supportIssues} → ${a.outcome.current.supportIssues}`}</p>}</details></article>}</Paged></section>}
    {data && <section hidden={view !== 'data'} className="data-panel"><CompanyEditor key={snapshot?.importKey || 'new-company'} snapshot={snapshot} busy={busy} readOnly={readOnly} onSave={value => perform(async () => { const current = await request(root, {}, token); if ((current.latest?.snapshot.importKey || null) !== (snapshot?.importKey || null)) throw new Error('Company data changed while you were editing. Keep a copy of your changes and reload before saving.'); await request(`${root}/import`, { method: 'POST', headers: { 'X-Base-Import-Key': snapshot?.importKey || '' }, body: JSON.stringify(value) }, token); setView('priorities'); setFilter('all'); setQuery(''); }, 'Observation saved. Company signals are updated.')}/><details className="advanced-import"><summary>Advanced: JSON import and sample data</summary><h3>Your company observation</h3><p className="muted">Refresh signals rechecks the same data. Import a newer observation to measure real changes.</p>{snapshot && <div className="data-counts">{['teams', 'employees', 'projects', 'features', 'customers'].map(key => <span key={key}><strong>{snapshot[key].length}</strong> {key}</span>)}</div>}{readOnly ? <p>Your workspace role allows viewing. A founder can import a newer observation.</p> : <><p>Choose a JSON file or prepare a sample, review it, then import. Existing observations remain available to measure action outcomes.</p><div className="import-tools"><button className="quiet-button" disabled={busy} onClick={() => setDraft(JSON.stringify(sampleSnapshot(), null, 2))}>Prepare sample data</button><label>Choose JSON file<input type="file" accept=".json,application/json" disabled={busy} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 900000) throw new Error('File must be smaller than 900 KB'); setDraft(await file.text()); setError(''); } catch (e) { setError(e.message); } }} /></label>{snapshot && <button className="quiet-button" disabled={busy} onClick={() => setDraft(JSON.stringify({ ...snapshot, importKey: `observation-${crypto.randomUUID()}`, observedAt: new Date().toISOString() }, null, 2))}>Edit latest observation</button>}</div><form onSubmit={e => { e.preventDefault(); perform(async () => { await send('/import', JSON.parse(draft)); setDraft(''); setView('priorities'); setFilter('all'); setQuery(''); }, 'Company data imported and signals updated.'); }}><label>Review snapshot JSON<textarea className="snapshot-editor" value={draft} onChange={e => setDraft(e.target.value)} required spellCheck={false} placeholder="Prepare a sample or choose a JSON file to get started."/></label><button disabled={busy || !draft}>{busy ? 'Validating…' : 'Validate and import →'}</button></form></>}</details></section>}
  </section>;
}
