import Paged from './Paged.jsx';
import React, { useEffect, useState } from 'react';
const prompts = ['Which teams have capacity problems?', 'What needs attention with customers?', 'What is our runway?', 'Which decisions have recorded lessons?', 'What actions are due?'];
export default function CompanyQuestions({ root, request, token, readOnly, onNavigate }) {
  const [items, setItems] = useState([]), [question, setQuestion] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; request(`${root}/questions`, {}, token).then(v => { if (active) setItems(v); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [root, token]);
  async function ask(e) { e.preventDefault(); setError(''); setBusy(true); try { const result = await request(`${root}/questions`, { method: 'POST', body: JSON.stringify({ question }) }, token); setItems(old => [result, ...old].slice(0, 30)); setQuestion(''); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <section className="data-panel"><p className="eyebrow">ASK GENESIS</p><h3>Answers with company evidence.</h3><p className="muted">Ask about recorded risks, customers, teams, finances, actions, decisions, or saved scenarios. This local evidence assistant retrieves matching records; it does not invent answers or require a model API key.</p><div className="question-prompts">{prompts.map(p => <button className="quiet-button" key={p} disabled={readOnly || busy} onClick={() => setQuestion(p)}>{p}</button>)}</div><form onSubmit={ask}><label>Your question<textarea value={question} onChange={e => setQuestion(e.target.value)} minLength={3} maxLength={2000} required disabled={readOnly || busy} placeholder="Ask about an account, team, decision, or financial baseline…"/></label><button disabled={readOnly || busy || question.trim().length < 3}>{busy ? 'Finding evidence…' : 'Ask Genesis'}</button></form>{error && <p role="alert" className="error">{error}</p>}{readOnly && <p className="muted">Viewer access can read saved questions. Recording new questions requires a founder role.</p>}<Paged items={items} size={2} resetKey={items[0]?._id || ""}>{item => <article className="question-answer" key={item._id}><h4>{item.question}</h4><details><summary>Read answer & supporting records</summary><p className="answer-text">{item.answer}</p><div className="evidence-links">{item.evidence.map((e, i) => <button key={e.id} className="quiet-button" onClick={() => onNavigate(e.view)}>[{i + 1}] {e.title} →</button>)}</div></details><p className="muted">Answered {new Date(item.createdAt).toLocaleString()}. Saved answers retain the evidence available at that time.</p></article>}</Paged></section>;
}
