import Paged from './Paged.jsx';
import React, { useState } from 'react';
const results = { achieved: 'Achieved', partial: 'Partially achieved', not_achieved: 'Not achieved', unknown: 'Not enough evidence' };
function CreateDecision({ snapshot, signals, actions, busy, onSave, onCancel }) {
  const [requestId] = useState(() => crypto.randomUUID());
  return <form className="decision-form" onSubmit={async e => { e.preventDefault(); const form = new FormData(e.currentTarget); const input = Object.fromEntries(form); input.requestId = requestId; input.actionIds = form.getAll('actionIds'); if (!input.signalKey) delete input.signalKey; await onSave(input); }}>
    <h3>Record a decision</h3><p className="muted">Capture what you chose and how you will know whether it worked.</p>
    <label>Decision<input name="title" placeholder="For example: move one engineer to account sync" required maxLength={160} autoFocus/></label>
    <div className="form-pair"><label>Owner<select name="ownerId" required><option value="self">Me</option>{snapshot?.employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Review on<input name="reviewDate" type="date" required/></label></div>
    <label>Why are we doing this?<textarea name="reason" required maxLength={4000} placeholder="The problem, evidence, and trade-offs behind this choice."/></label>
    <label>Expected result<textarea name="expectedResult" required maxLength={4000} placeholder="An observable result and the period you expect it within."/></label>
    <label>Alternatives considered · optional<textarea name="alternatives" maxLength={4000}/></label>
    <label>Related signal · optional<select name="signalKey"><option value="">Standalone decision</option>{signals.map(s => <option key={s.key} value={s.key}>{s.title}</option>)}</select></label>
    {!!actions.length && <fieldset><legend>Related actions · optional, up to 10</legend><div className="relationship-options">{actions.map(a => <label key={a._id}><input name="actionIds" type="checkbox" value={a._id}/>{a.title} · {a.status.replaceAll('_', ' ')}</label>)}</div></fieldset>}
    <div className="card-controls"><button type="button" className="quiet-button" disabled={busy} onClick={onCancel}>Cancel</button><button disabled={busy}>{busy ? 'Saving…' : 'Save decision'}</button></div>
  </form>;
}
function ReviewDecision({ decision, busy, onSave, onCancel }) {
  const [requestId] = useState(() => crypto.randomUUID());
  return <form className="decision-form" onSubmit={async e => { e.preventDefault(); const input = Object.fromEntries(new FormData(e.currentTarget)); input.requestId = requestId; if (!input.nextReviewDate) delete input.nextReviewDate; await onSave(input); }}><h4>Review the outcome</h4><p className="muted">Expected: {decision.expectedResult}</p><label>Assessment<select name="result" required><option value="unknown">Not enough evidence</option>{Object.entries(results).filter(([k]) => k !== 'unknown').map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>What actually happened?<textarea name="actualResult" required maxLength={4000}/></label><label>What did we learn?<textarea name="lesson" required maxLength={4000} placeholder="What should inform the next decision?"/></label><label>Follow-up review · optional<input name="nextReviewDate" type="date"/></label><p className="muted">Without a follow-up date, this decision is marked reviewed. Your assessment is recorded separately from company evidence; it does not establish causation.</p><div className="card-controls"><button type="button" className="quiet-button" disabled={busy} onClick={onCancel}>Cancel review</button><button disabled={busy}>{busy ? 'Saving…' : 'Save outcome & lesson'}</button></div></form>;
}
function EvidenceComparison({ baseline, current }) {
  if (!baseline) return <p className="muted">No signal evidence was linked when this decision was recorded.</p>;
  const labels = { allocatedHours: 'Weekly allocated hours', capacityHours: 'Weekly capacity hours', delayDays: 'Overdue days', supportIssues: 'Open support issues', customerCount: 'Connected customers', concentrationPct: 'Concentration (%)', daysToRenewal: 'Days until renewal', completion: 'Project completion (%)' };
  const keys = Object.keys(labels).filter(k => baseline[k] !== undefined || current?.[k] !== undefined);
  return <><div className="table-scroll"><table><thead><tr><th>Evidence</th><th>At decision</th><th>Latest signal</th></tr></thead><tbody>{keys.map(k => <tr key={k}><td>{labels[k]}</td><td>{baseline[k] ?? 'Unknown'}</td><td>{current?.[k] ?? 'Unavailable'}</td></tr>)}</tbody></table></div><p className="muted">A missing signal is not proof of success. Compare dates, customer coverage, and your recorded outcome.</p></>;
}
export default function DecisionMemory({ decisions, snapshot, signals, actions, busy, readOnly, onCreate, onReview, onOpenActions }) {
  const [creating, setCreating] = useState(false), [reviewing, setReviewing] = useState(null), [query, setQuery] = useState(''), [filter, setFilter] = useState('all');
  const today = new Date().toISOString().slice(0, 10);
  const due = decisions.filter(d => d.status === 'open' && d.reviewDate <= today);
  const visible = decisions.filter(d => (filter === 'all' || (filter === 'due' ? d.status === 'open' && d.reviewDate <= today : d.status === filter)) && `${d.title} ${d.reason} ${d.ownerName} ${d.reviews.map(r => r.lesson).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => (a.status === 'open' ? 0 : 1) - (b.status === 'open' ? 0 : 1) || a.reviewDate.localeCompare(b.reviewDate));
  return <section className="decision-memory"><div className="section-heading"><div><p className="eyebrow">DECISION MEMORY</p><h3>Remember the why. Learn from the result.</h3><p className="muted">Keep your decisions, expectations, and lessons connected to company evidence.</p></div>{!readOnly && !creating && <button disabled={busy} onClick={() => setCreating(true)}>+ Record decision</button>}</div>
    {!!due.length && <button className="decision-due" onClick={() => setFilter('due')}>{due.length} decision{due.length === 1 ? '' : 's'} ready for review →</button>}
    {creating && <CreateDecision snapshot={snapshot} signals={signals} actions={actions} busy={busy} onCancel={() => setCreating(false)} onSave={async input => { if (await onCreate(input)) setCreating(false); }}/>}
    <div className="priority-toolbar"><label className="search-label">Search decisions and lessons<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Decision, owner, or lesson…"/></label><label>Show<select value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All decisions</option><option value="due">Due for review</option><option value="open">Awaiting review</option><option value="reviewed">Reviewed</option></select></label></div>
    {!visible.length && <div className="empty-state"><h4>No matching decisions</h4><p>Record a choice and its expected result, then come back to review what happened.</p></div>}
    <Paged items={visible} size={2} resetKey={`${query}:${filter}`}>{d => { const signal = signals.find(s => s.key === d.signalKey); const linked = actions.filter(a => d.actionIds.includes(a._id)); return <article className="decision-card" key={d._id}><div className="card-top"><span className="signal-badge">{d.status === 'reviewed' ? 'Reviewed' : 'Awaiting review'}</span>{d.status === 'open' && d.reviewDate <= today && <span className="signal-badge warning">Review due</span>}<span className="muted">{d.ownerName} · Review {d.reviewDate}</span></div><h3>{d.title}</h3><p><strong>Expected:</strong> {d.expectedResult}</p><details><summary>Reasoning, evidence & linked work</summary><p><strong>Why:</strong> {d.reason}</p>{d.alternatives && <p><strong>Alternatives:</strong> {d.alternatives}</p>}<p className="muted">Recorded by {d.createdByName} on {new Date(d.createdAt).toLocaleDateString()} · Original review date {d.initialReviewDate || d.reviewDate}</p>{d.signalTitle && <p><strong>Linked signal:</strong> {d.signalTitle}</p>}<p className="muted">Baseline observation: {d.baselineObservedAt ? new Date(d.baselineObservedAt).toLocaleString() : 'None'} · Latest observation: {snapshot ? new Date(snapshot.observedAt).toLocaleString() : 'None'}</p>{d.baselineSource?.kind === 'sample' && <p className="sample-notice">Decision baseline uses synthetic sample data.</p>}<EvidenceComparison baseline={d.baseline} current={signal?.evidence}/>{!!d.actionIds.length && <><h4>Linked actions</h4>{linked.map(a => <p key={a._id}>{a.title} · {a.ownerName} · {a.status.replaceAll('_', ' ')}</p>)}{linked.length < d.actionIds.length && <p className="muted">Some linked actions are outside the currently loaded list.</p>}<button className="quiet-button" onClick={onOpenActions}>Open actions →</button></>}</details>
      {!!d.reviews.length && <section className="decision-timeline"><h4>Outcome history</h4>{[...d.reviews].reverse().map((r, i) => <details key={r._id || i} ><summary>{results[r.result]} · {new Date(r.reviewedAt).toLocaleDateString()}</summary><p><strong>Actual result:</strong> {r.actualResult}</p><p><strong>Lesson:</strong> {r.lesson}</p><p className="muted">Recorded by {r.reviewerName}{r.nextReviewDate ? ` · Follow-up ${r.nextReviewDate}` : ''}</p>{r.source?.kind === 'sample' && <p className="muted">Review evidence uses synthetic sample data.</p>}{r.evidence && <details><summary>Company evidence at this review</summary><EvidenceComparison baseline={d.baseline} current={r.evidence}/><p className="muted">Observed {new Date(r.observedAt).toLocaleString()}</p></details>}</details>)}</section>}
      {!readOnly && (reviewing === d._id ? <ReviewDecision decision={d} busy={busy} onCancel={() => setReviewing(null)} onSave={async input => { if (await onReview(d._id, input)) setReviewing(null); }}/> : <button className="quiet-button" disabled={busy || d.reviews.length >= 50} onClick={() => setReviewing(d._id)}>{d.reviews.length ? 'Add another review' : 'Review outcome'}</button>)}
    </article>; }}</Paged>
    <p className="muted">Showing the latest {decisions.length} decision records, up to 100. Due dates are evaluated in UTC.</p>
  </section>;
}
