import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io } from 'socket.io-client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:3001';
async function request(path, options = {}, token) { let res; try { res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); } catch { throw new Error(`Cannot reach the Genesis API at ${API}. Start the API service, then try again.`); } const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Request failed'); return data; }

function Auth({ onAuthenticated }) { const [mode, setMode] = useState('register'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); async function submit(e) { e.preventDefault(); try { const result = await request(`/api/auth/${mode}`, { method: 'POST', body: JSON.stringify(form) }); onAuthenticated(result); } catch (e) { setError(e.message); } } return <main className="auth"><section><p className="eyebrow">GENESIS / FOUNDER INTELLIGENCE</p><h1>Make the next decision before it makes you.</h1><p>Grounded startup analysis, live runway, and competitor signals in one self-hosted workspace.</p></section><form onSubmit={submit}><h2>{mode === 'register' ? 'Create your workspace' : 'Welcome back'}</h2>{mode === 'register' && <input placeholder="Your name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/>}<input placeholder="Email" type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><input placeholder="Password (8+ characters)" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/>{error && <p className="error">{error}</p>}<button>{mode === 'register' ? 'Start building' : 'Sign in'}</button><a className="oauth" href={`${API}/api/auth/google`}>Continue with Google</a><button type="button" className="link" onClick={() => setMode(mode === 'register' ? 'login' : 'register')}>{mode === 'register' ? 'Already have an account?' : 'Need an account?'}</button></form></main> }

function App() { const [session, setSession] = useState(() => { const oauthToken = new URLSearchParams(location.search).get('token'); if (oauthToken) { const value = { token: oauthToken }; localStorage.setItem('genesis-session', JSON.stringify(value)); history.replaceState({}, '', location.pathname); return value; } return JSON.parse(localStorage.getItem('genesis-session') || 'null'); }); const [workspaces, setWorkspaces] = useState([]); const [workspace, setWorkspace] = useState(null); const [events, setEvents] = useState([]); const [alerts, setAlerts] = useState([]); const [run, setRun] = useState(null); const [finance, setFinance] = useState({ cash: '', monthlyRevenue: '', monthlyExpenses: '' }); const [competitor, setCompetitor] = useState(''); const [workspaceName, setWorkspaceName] = useState(''); const token = session?.token;
  async function load() { const items = await request('/api/workspaces', {}, token); setWorkspaces(items); if (items[0]) setWorkspace(items[0]); }
  useEffect(() => { if (token) load().catch(console.error); }, [token]);
  useEffect(() => { if (!workspace) return; const socket = io(API, { auth: { token } }); socket.emit('workspace:join', workspace._id); socket.on('agent:progress', e => setEvents(old => [...old, e])); socket.on('alert:created', a => setAlerts(old => [a, ...old])); return () => socket.close(); }, [workspace?._id, token]);
  if (!session) return <Auth onAuthenticated={s => { localStorage.setItem('genesis-session', JSON.stringify(s)); setSession(s); }}/>;
  async function createWorkspace(e) { e?.preventDefault(); const name = workspaceName.trim(); if (!name) return; const w = await request('/api/workspaces', { method: 'POST', body: JSON.stringify({ name }) }, token); setWorkspaces([...workspaces, w]); setWorkspace(w); setWorkspaceName(''); }
  async function analyze(e) { e.preventDefault(); const idea = new FormData(e.currentTarget).get('idea'); const newRun = await request(`/api/runs/workspaces/${workspace._id}/idea-analysis`, { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ idea }) }, token); setRun(newRun); setEvents([]); }
  async function saveFinance(e) { e.preventDefault(); const result = await request(`/api/workspaces/${workspace._id}/financials`, { method: 'POST', body: JSON.stringify(Object.fromEntries(Object.entries(finance).map(([k,v]) => [k, Number(v)]))) }, token); setAlerts(a => [result.runway, ...a]); }
  async function addCompetitor(e) { e.preventDefault(); await request(`/api/workspaces/${workspace._id}/competitors`, { method: 'POST', body: JSON.stringify({ name: competitor }) }, token); setCompetitor(''); await load(); }
  const workspaceForm = <form className="workspace-form" onSubmit={createWorkspace}><input aria-label="Workspace name" placeholder="Workspace name" value={workspaceName} onChange={e => setWorkspaceName(e.target.value)} required/><button>Create workspace</button></form>;
  return <div className="shell"><aside><p className="eyebrow">GENESIS</p>{workspaceForm}{workspaces.map(w => <button className={w._id === workspace?._id ? 'selected' : ''} key={w._id} onClick={() => setWorkspace(w)}>{w.name}</button>)}<button className="link logout" onClick={() => { localStorage.removeItem('genesis-session'); setSession(null); }}>Sign out</button></aside><main>{workspace ? <><header><div><p className="eyebrow">WORKSPACE</p><h1>{workspace.name}</h1></div><div className="alerts">{alerts.slice(0,3).map(a => <p key={a._id || a.title} className={a.severity}>{a.title || `${a.runwayMonths} months runway`}</p>)}</div></header><section className="grid"><article className="wide"><h2>Foundation analysis</h2><form onSubmit={analyze}><textarea name="idea" defaultValue={workspace.idea} minLength="20" placeholder="Describe the startup: customer, problem, approach, and why now."/><button>Run seven-agent analysis</button></form><Trace events={events} run={run}/></article><article><h2>Financial survival</h2><form onSubmit={saveFinance}><label>Cash<input type="number" required value={finance.cash} onChange={e=>setFinance({...finance,cash:e.target.value})}/></label><label>Monthly revenue<input type="number" required value={finance.monthlyRevenue} onChange={e=>setFinance({...finance,monthlyRevenue:e.target.value})}/></label><label>Monthly expenses<input type="number" required value={finance.monthlyExpenses} onChange={e=>setFinance({...finance,monthlyExpenses:e.target.value})}/></label><button>Update runway</button></form></article><article><h2>Competitor watch</h2><form onSubmit={addCompetitor}><input placeholder="Competitor name" value={competitor} onChange={e=>setCompetitor(e.target.value)}/><button>Add competitor</button></form><ul>{workspace.competitors?.map(c=><li key={c._id}>{c.name}</li>)}</ul><p className="muted">Your digest is queued daily at 07:00 UTC after competitors are added.</p></article></section></> : <section className="empty-workspace"><p className="eyebrow">GET STARTED</p><h1>Create your first workspace</h1><p>A workspace holds the idea analysis, financial survival data, and competitor watchlist for one company.</p>{workspaceForm}</section>}</main></div> }
function Trace({ events, run }) { const agents = ['market_research','risk_analysis','legal_scout','competitive_intelligence','assumption_stress_tester','financial_modelling','pitch_writer']; const states = Object.fromEntries(events.filter(e=>e.agent).map(e=>[e.agent,e.type])); return <div className="trace"><h3>{run ? `Analysis ${run.status}` : 'Agent trace'}</h3><div className="agent-grid">{agents.map(a=><div key={a} className={states[a] === 'agent_finished' ? 'done' : states[a] === 'agent_started' ? 'running' : ''}>{a.replaceAll('_',' ')}</div>)}</div>{events.filter(e=>e.type === 'agent_finished').map((e,i)=><details key={i}><summary>{e.agent} · {e.status}</summary><pre>{JSON.stringify(e.output, null, 2)}</pre></details>)}</div> }
createRoot(document.getElementById('root')).render(<App/>);
