import React, { useState } from 'react';
const money = (minor, currency) => `${currency} ${(minor / 100).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
export default function TeamIntelligence({ health, snapshot, signals, actions, readOnly, busy, onRefresh, onData, onPriority, onActions, onDecisions }) {
  const [selected, setSelected] = useState(null), [query, setQuery] = useState(''), [pressureOnly, setPressureOnly] = useState(false);
  if (!snapshot) return <section className="empty-state"><h3>Understand your team’s capacity.</h3><p>Add teams, employees, project ownership, and customer dependencies to see where work needs attention.</p><button onClick={onData}>Open company data →</button></section>;
  if (!health) return <section className="empty-state"><h3>Team analysis is ready to calculate.</h3><p>Refresh the saved observation to include the new team intelligence rules.</p><button disabled={readOnly || busy} onClick={onRefresh}>Refresh team analysis</button>{readOnly && <p className="muted">A founder can refresh now; the scheduled recheck also updates analysis.</p>}</section>;
  const allTeams = [...health.teams].sort((a, b) => b.excessHours - a.excessHours || b.flags.length - a.flags.length || a.name.localeCompare(b.name));
  const visible = allTeams.filter(t => t.name.toLowerCase().includes(query.toLowerCase()) && (!pressureOnly || t.flags.length > 0));
  const team = visible.find(t => t.id === selected) || visible[0];
  const linkedSignals = team ? signals.filter(s => s.paths.some(p => p.teamId === team.id)) : [];
  const keys = new Set(linkedSignals.map(s => s.key));
  const linkedActions = team ? actions.filter(a => keys.has(a.riskKey) || team.employees.some(e => e.id === a.ownerId)) : [];
  return <section className="team-intelligence"><div className="section-heading"><div><p className="eyebrow">TEAM CAPACITY</p><h3>Can your teams deliver what’s next?</h3><p className="muted">Review planned work, ownership, deadlines, and customer dependencies together.</p></div><button className="quiet-button" onClick={onData}>Update team data</button></div>
    <div className="team-overview"><span><strong>{health.teams.length}</strong> teams</span><span><strong>{health.teams.reduce((n, t) => n + t.employees.filter(e => e.excessHours > 0).length, 0)}</strong> people above planned capacity</span><span><strong>{health.teams.reduce((n, t) => n + t.projects.filter(p => p.daysUntilDue < 0).length, 0)}</strong> overdue projects</span></div>
    <p className="muted">Observed {new Date(health.observedAt).toLocaleString()} · Evaluated {new Date(health.evaluatedAt).toLocaleString()}</p>
    <div className="priority-toolbar"><label className="search-label">Find a team<input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search team names…"/></label><label className="graph-toggle"><input type="checkbox" checked={pressureOnly} onChange={e => setPressureOnly(e.target.checked)}/>Only teams with review flags</label></div>
    {!visible.length && <div className="empty-state"><h4>No teams match this view</h4><p>Adjust the search or add teams in Company data.</p></div>}
    <div className="team-selector">{visible.map(t => <button key={t.id} aria-pressed={team?.id === t.id} className={team?.id === t.id ? 'active' : ''} onClick={() => setSelected(t.id)}><strong>{t.name}</strong><span>{t.employees.length} people · {t.projects.length} active projects</span><small>{t.flags.length} review flags · {t.allocatedHours}/{t.capacityHours}h allocated</small></button>)}</div>
    {team && <section className="team-focus"><div className="section-heading"><h3>{team.name}</h3><span className="signal-badge">{team.flags.length ? `${team.flags.length} items to review` : 'No current rule flags'}</span></div><div className="evidence-metrics"><div><strong>{team.allocatedHours} / {team.capacityHours}h</strong><span>Weekly allocation / capacity</span></div><div><strong>{team.excessHours}h</strong><span>Total individual overload</span></div><div><strong>{team.availableHours}h</strong><span>Unallocated hours across people</span></div><div><strong>{money(team.arrMinor, health.currency)}</strong><span>ARR connected to active projects</span></div></div>
      <div className="team-capacity-track" role="img" aria-label={team.utilizationPct === null ? 'Utilization unavailable because recorded capacity is zero' : `Team allocation is ${team.utilizationPct}% of capacity`}><span style={{ width: `${Math.min(100, team.utilizationPct || 0)}%` }} className={team.allocatedHours > team.capacityHours ? 'overloaded' : ''}/></div><p className="muted">{team.utilizationPct === null ? 'Utilization unavailable: no positive capacity recorded.' : `${team.utilizationPct}% allocated`} · {team.workloadChangePct === null ? `Trend unavailable: ${team.baselineReason.toLowerCase()}.` : `${team.workloadChangePct > 0 ? '+' : ''}${team.workloadChangePct}% allocation change since ${new Date(health.previousObservedAt).toLocaleDateString()}`}</p>
      {team.excessHours > 0 && team.availableHours > 0 && <p className="sample-notice">Overload and available hours coexist in this team. A team-wide total can hide individual pressure; skills and commitments must be considered before reallocating work.</p>}
      {!!team.recommendations.length && <section className="team-recommendations"><h4>What to review next</h4><ul>{team.recommendations.map(r => <li key={r}>{r}</li>)}</ul><button className="quiet-button" onClick={onDecisions}>Open decision memory →</button></section>}
      <details open><summary>People & ownership</summary><p className="muted">These are workload and assignment records, not performance rankings. Shared ownership counts once for each named owner.</p><div className="table-scroll"><table><thead><tr><th>Person</th><th>Allocation / capacity</th><th>Above capacity</th><th>Unallocated</th><th>Active projects owned</th><th>Sole-owner projects</th></tr></thead><tbody>{team.employees.map(e => <tr key={e.id}><td>{e.name}</td><td>{e.allocatedHours} / {e.capacityHours}h</td><td>{e.excessHours}h</td><td>{e.availableHours}h</td><td>{e.ownedProjectIds.length}</td><td>{e.soleOwnerProjectIds.length}</td></tr>)}</tbody></table></div>{!team.employees.length && <p className="muted">No employee capacity records are available.</p>}</details>
      <details open><summary>Active projects & connected customers</summary>{!team.projects.length && <p className="muted">No unfinished projects are assigned to this team.</p>}{team.projects.map(p => <article className="team-project" key={p.id}><div className="section-heading"><strong>{p.name}</strong><span className={`signal-badge ${p.daysUntilDue < 0 ? 'warning' : ''}`}>{p.daysUntilDue < 0 ? `${-p.daysUntilDue} days overdue` : `Due in ${p.daysUntilDue} days`}</span></div><p>{p.completion}% complete · Due {p.dueDate} · {p.ownerIds.map(id => team.employees.find(e => e.id === id)?.name || 'Missing owner').join(', ') || 'No owner assigned'}</p><p>{p.customers.length} connected customers · {money(p.arrMinor, health.currency)} ARR</p><p className="muted">Features: {p.features.map(f => f.name).join(', ') || 'No linked features'}</p>{!!p.flags.length && <ul>{p.flags.map(f => <li key={f.kind}>{f.title}</li>)}</ul>}{!!p.customers.length && <details><summary>Inspect customer dependencies</summary><ul>{p.customers.map(c => <li key={c.id}>{c.name} · {money(c.arrMinor, health.currency)} ARR · Renewal {c.renewalDate || 'unknown'}</li>)}</ul></details>}</article>)}</details>
      <div className="graph-context"><section><h4>Linked priorities</h4>{linkedSignals.map(s => <button className="graph-signal" key={s.key} onClick={() => onPriority(s.key)}>{s.title}<span>Open priority →</span></button>)}{!linkedSignals.length && <p className="muted">No current priority explicitly references this team. Team review flags are not automatically promoted to financial risks.</p>}</section><section><h4>Linked actions</h4>{linkedActions.slice(0, 5).map(a => <p key={a._id}>{a.title} · {a.ownerName} · {a.status.replaceAll('_', ' ')}</p>)}{linkedActions.length ? <button className="quiet-button" onClick={onActions}>Open actions ({linkedActions.length}) →</button> : <p className="muted">No loaded actions are linked to this team’s signals or assigned to its people.</p>}</section></div>
      <details><summary>All review flags and rule definitions</summary><ul>{team.flags.map((f, i) => <li key={i}>{f.title}</li>)}</ul><p className="muted">Deadline pressure means due within {health.rules.deadlineDays} days and below {health.rules.completionThreshold}% completion. Ownership concentration means owning/co-owning at least {health.rules.minimumOwnedProjects} active projects and at least {health.rules.ownershipSharePct}% of the team’s active projects. A sole owner is a backup-coverage prompt, not proof of a bottleneck.</p><ul className="muted">{health.limitations.map(l => <li key={l}>{l}</li>)}</ul></details>
    </section>}
  </section>;
}
